name: Code Quality - JavaScript 
on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: Denocord/deno-action@master
              with:
                args: '["fmt", ".", "--check"]'
